create table course(
    course_id int4 primary key not null generated by default as identity,
    course_name varchar(100) not null,
    par int4 not null,
    unique (course_id, course_name, par)
);
create index course_name_idx on course (course_name);

create table hole (
    course_id int4 not NULL,
    hole_number int4 not NULL,
    par int4 not NULL,
    constraint course_hole_pk primary key (course_id, hole_number),
    constraint course_id_fk foreign key (course_id) references public.course(course_id),
    unique (course_id, hole_number, par)
);

create table round_score (
    course_id int4 not NULL,
    round_id uuid not null,
    course_name varchar(100) not null,
    user_id varchar(30) not null,
    par int4 not null,
    round_score int4,
    date_played Date not null default CURRENT_DATE,
    constraint round_score_pk primary key (course_id, round_id),
    constraint course_id_fk foreign key (course_id, course_name, par) references public.course(course_id, course_name, par)
);


create table hole_score(
    course_id int4 not NULL,
    round_id uuid not null ,
    hole_number int4 not null,
    par int4,
    score int4 not null,
    gir boolean,
    fairway boolean,
    putts int4,
    constraint hole_score_pk primary key (course_id, round_id, hole_number),
    constraint round_score_fk foreign key (course_id, round_id) references public.round_score(course_id, round_id),
    constraint course_hole_fk foreign key (course_id, hole_number, par) references public.hole (course_id, hole_number, par)
);


insert into course (course_name, par) values ('River Oaks Golf Course', 71);

insert into hole (course_id, hole_number, par) values (1, 1, 5);
insert into hole (course_id, hole_number, par) values (1, 2, 4);
insert into hole (course_id, hole_number, par) values (1, 3, 4);
insert into hole (course_id, hole_number, par) values (1, 4, 3);
insert into hole (course_id, hole_number, par) values (1, 5, 4);
insert into hole (course_id, hole_number, par) values (1, 6, 4);
insert into hole (course_id, hole_number, par) values (1, 7, 3);
insert into hole (course_id, hole_number, par) values (1, 8, 4);
insert into hole (course_id, hole_number, par) values (1, 9, 4);

insert into hole (course_id, hole_number, par) values (1, 10, 4);
insert into hole (course_id, hole_number, par) values (1, 11, 4);
insert into hole (course_id, hole_number, par) values (1, 12, 3);
insert into hole (course_id, hole_number, par) values (1, 13, 5);
insert into hole (course_id, hole_number, par) values (1, 14, 4);
insert into hole (course_id, hole_number, par) values (1, 15, 4);
insert into hole (course_id, hole_number, par) values (1, 16, 3);
insert into hole (course_id, hole_number, par) values (1, 17, 4);
insert into hole (course_id, hole_number, par) values (1, 18, 5);

CREATE TABLE public.current_round (
    user_id varchar(60) NOT NULL,
    round_id uuid NOT NULL,
    course_id int4 NOT NULL,
    relation_to_par int4 NOT NULL,
    holes_played int4 NOT NULL,
    tournament_id int4 NULL,
    CONSTRAINT current_round_pk PRIMARY KEY (user_id)
);
